### ISSUE TITLE
fails with sqlite 3.41.2 ?

### ISSUE THREAD

**Issue by landryb** [kristapsdz/sqlite2mdoc#4] opened 2023-05-06 07:39 UTC
on the recent sqlite versions, producing the mdoc/manpage fails:
```
/usr/local/bin/sqlite2mdoc -p /usr/obj/ports/sqlite3-3.41.2/fake-amd64/usr/local/man/man3 /usr/obj/ports/sqlite3-3.41.2/fake-amd64/usr/local/include/sqlite3.h
sqlite2mdoc: /usr/obj/ports/sqlite3-3.41.2/fake-amd64/usr/local/include/sqlite3.h:768: warn: unexpected end of interface description
sqlite2mdoc: /usr/obj/ports/sqlite3-3.41.2/fake-amd64/usr/local/include/sqlite3.h:733: interface has errors, not producing manpage
```

**Comment by kristapsdz** [comment] 2023-05-06 18:38
That looks like a typo in their header file, but I'll make the mdoc-generator account for it.  Thanks for the report Laundry!

**Comment by kristapsdz** [comment] 2023-05-06 21:42
Fixed with the above.  Please let me know if the issue is fixed on your end and I'll close this issue and create a new version.  Thanks again!

**Comment by landryb** [comment] 2023-05-09 07:39
can confirm that 3.41.2 is happy with it.

```
/usr/local/bin/sqlite2mdoc -p /usr/obj/ports/sqlite3-3.41.2/fake-amd64/usr/local/man/man3 /usr/obj/ports/sqlite3-3.41.2/fake-amd64/usr/local/include/sqlite3.h
```

tried it by just adding those 3 lines to `converters/sqlite2mdoc` port (and commenting MASTER_SITES):
```
+GH_ACCOUNT=    kristapsdz
+GH_PROJECT=sqlite2mdoc
+GH_COMMIT=     5f9fcbbbf36db7aaa5a52ebbd694df8bbdffa632
```


**edit**: a new manpage was generated, `man/man3/sqlite3_io_methods.3`

**Comment by kristapsdz** [comment] 2023-05-09 16:56
How is that new?  I see it in OpenBSD 7.2.
```
% pkg_locate sqlite3_io_methods
sqlite3-3.39.3:databases/sqlite3:/usr/local/man/man3/sqlite3_io_methods.3
```
If this doesn't look like an issue to you, I'll bag and tag a release.

**Comment by landryb** [comment] 2023-05-10 06:28
> How is that new? I see it in OpenBSD 7.2.
> 
> ```
> % pkg_locate sqlite3_io_methods
> sqlite3-3.39.3:databases/sqlite3:/usr/local/man/man3/sqlite3_io_methods.3
> ```

well, it "disappeared" in 3.41, maybe when sqlite2mdoc started failing on the header :) cf https://github.com/openbsd/ports/commit/3f613ca67e1be2b4437f617487c583d726499d70#diff-4f27b2b9808f88f778aa635b432d87454e64b03b360376a48d1b7c2883a71596

> If this doesn't look like an issue to you, I'll bag and tag a release.

yes please, that'll allow us to update the sqlite2mdoc port, and readd the missing manpage to the sqlite port.

**Comment by kristapsdz** [comment] 2023-05-12 05:10
Thanks for looking this over.  I've tagged out a release as well: the source may be downloaded from GH and I also keep a signed copy in the snapshot directory on bsd.lv noted in the readme.

**Closed as completed by kristapsdz** 2023-05-12 05:10 UTC
